import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@/app/globals.css"
import { ClerkProvider } from "@clerk/nextjs"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Auth Layout",
  description: "Generated by create next app"
}

export default function AuthLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="h-screen flex justify-center items-center">{children}</div>
        </body>
      </html>
    </ClerkProvider>
  )
}
